name = "xaviadec"
main = "_worker.js"
compatibility_date = "2023-05-26"
# node_compat = true
workers_dev = true

[vars]
# PROXYIP = "206.237.98.76"
UUID = "cc316564-493d-47b9-b2cc-6972d5afdcf9"
# SOCKS5 = "127.0.0.1:1080"
# SOCKS5_RELAY = "true"
